# Generated by Django 4.2.3 on 2023-07-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
